### ISSUE TITLE
[Leia] Problem with air flow?

### ISSUE THREAD

**Issue by jbon** [Gillou38/Drying-open-source-solution#11]
the red beams on the image may block the air flow on the front and the rear of the first and the last drawer row.

![image](https://user-images.githubusercontent.com/7082390/34385011-00aa51be-eb20-11e7-97a9-e837e9478b69.png)

**Comment by jbon** [comment]
there are actually 5 beams potentially either creating turbulence in the air flow or blocking its way.

Maybe it would be better to have the beam structure outside of the rooms built by the panels, instead of having them inside.

![image](https://user-images.githubusercontent.com/7082390/34484957-59299da2-efc8-11e7-9acf-e7dfb739e78e.png)

**Comment by Gillou38** [comment]
If we use a beam with a section sizing 50 x 20, we can delete optimize it.
But It need to change the structure.

**Comment by Gillou38** [comment]
I modify beam section to optimize it.
