### ISSUE TITLE
[Leia] decide upon plenum design

### ISSUE THREAD

**Issue by jbon** [Gillou38/Drying-open-source-solution#13]
On the [provided sketch](https://github.com/Gillou38/Drying-open-source-solution/blob/master/02%20-%20Developing/Dryer%20Le%C3%AFa/Original%20design%20V2.jpg) specifies one plenum each 30cm, each plenum having the same orientation and size. 

I doubt this is the best was to force the air flow going up in the drawer towers. I think the plenums will create turbulence and hinder good air flow. Moreover, I think the specified system will create a imbalance in air flows between the first and the last drawer tower (the first tower becomes more air than the last). 

In order to support the discussion, I provided three different designs:
- one according to the provided specification: [option 1](https://github.com/jbon/Drying-open-source-solution/blob/master/02%20-%20Developing/Dryer%20Le%C3%AFa/CAD/STL%20exports/Structure_alternativePlenum1.stl)
- one with the same amount of plenums but with progressive angles. [option 2](https://github.com/jbon/Drying-open-source-solution/blob/master/02%20-%20Developing/Dryer%20Le%C3%AFa/CAD/STL%20exports/Structure.stl)
- one with only one oblique plan [option 3](https://github.com/jbon/Drying-open-source-solution/blob/master/02%20-%20Developing/Dryer%20Le%C3%AFa/CAD/STL%20exports/Structure_alternativePlenum2.stl)

I think the option 2 is the best, because there is no turbulence created, the air flow will be smoothly distributed among all towers, and it is easy to fabricate.

**Comment by Gillou38** [comment]
I think option 2 and 3 work.
option 3 : maybe the best but, I'm not sure, very regularly and easy to make. 
option 2 : create more turbulence, and could increase efficiency, I'm not sure.

**Comment by Gillou38** [comment]
Option 3 doesn't work. Need to break the airflow.

"Honnêtement je n'y crois pas trop. Pour le bas tu ne casses pas le flux
pour qu'il se répartisse de manière homogène, il est juste guidé, la
première armoire n'aura pas grand chose et peut être aussi la deuxième"

Best solution is 2.
