### ISSUE TITLE
[Leia] Define materials and production processes

### ISSUE THREAD

**Issue by jbon** [Gillou38/Drying-open-source-solution#7]
I can only go further in the modeling if I have an idea of what kind of materials fabrication processes can be used. Would you use, solid wood, plywood or metal for the structure? What kind of grate would you like to use for the drawers (fr.: claies)? The structure of the towers depends on this.

**Comment by Gillou38** [comment]
French document with listing of material p 21 : 
https://github.com/Gillou38/Drying-open-source-solution/blob/master/00%20-%20General/00%20-%20Ressource/Le%20s%C3%A9chage%20des%20PPAM%20par%20d%C3%A9shumidification.pdf
